name: Build, Generate Docs and Deploy React Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Generate Documentation
        run: |
          npm install jsdoc
          jsdoc -c jsdoc-frontend.json

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          CI=false npm run build

      - name: Deploy to Firebase Hosting
        run: |
          cd frontend
          npm install -g firebase-tools
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
